# Generated by Django 2.1.4 on 2019-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todo', models.CharField(max_length=120)),
                ('summery', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
